In [14]:
import numpy as np

# 연습문제 풀이
a = np.zeros((3, 3))
b = np.ones((3, 2))
c = np.arange(10, 160, 10)
c = c.reshape(3, 5)

aa = np.hstack([a, b])
bb = np.vstack([aa, c])
cc = np.tile(bb, (2, 1))
cc

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [45]:
import numpy as np
a = np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])
eng_rank = np.argsort(a[1, :])
a[:, eng_rank[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [14]:
import numpy as np
a = np.array([1, 2, 2, 3, 5, 6])
np.bincount(a, minlength=7) # 0부터 6까지

array([0, 1, 2, 1, 0, 1, 1], dtype=int64)